### ISSUE TITLE
When printing a gcode file in a folder the gcode preview image is not shown in discord. 

### ISSUE THREAD

**Issue by samwiseg0** [eliteSchwein/mooncord#152]
#### Issue description
When printing a gcode file in a folder the gcode preview image is not shown.

#### Steps to reproduce the issue
1.  Upload a gcode file to klipper/moonraker.
2. Organize it into a folder
3. Send the file to print
4. Observe that the notification is using the generic image for the file and not the preview image

#### What's the expected result?
When printing from a subfolder the preview image should be present in the notification on discord. 

#### What's the actual result?
The preview image is the default and not the one contained in the gcode file. 

#### Additional details / screenshot
In a subfolder.
![Screen Shot 2021-11-09 at 2 51 29 PM](https://user-images.githubusercontent.com/2241731/140994793-0c12b840-8046-45a6-a154-a6c793c97d17.png)

Not in a subfolder.
![Screen Shot 2021-11-09 at 2 52 32 PM](https://user-images.githubusercontent.com/2241731/140994954-278344d0-6323-4e17-9279-d256d410fd7d.png)

 
#### Version Info
`MoonCord v0.0.4-14`

**Comment by eliteSchwein** [comment]
i will fix that with 0.0.5, since its only aesthetics there will be no hotfix for that in 0.0.4

**Comment by eliteSchwein** [comment]
resolved in 0.0.5

**Comment by samwiseg0** [comment]
This still appears to be an issue
<img width="593" alt="Screen Shot 2022-01-07 at 6 42 31 PM" src="https://user-images.githubusercontent.com/2241731/148620857-28d10dff-7f9d-4c07-ac05-554a8229b776.png">
?

**Comment by samwiseg0** [comment]
I confirmed this is an issue when retrieving the file. It is missing the sub folder path. 

```
[error] [2022-01-08T22:23:35.166Z] Thumbnail Error:
[error] [2022-01-08T22:23:35.167Z] Url: http://127.0.0.1/server/files/gcodes/.thumbs/SB_CW2_beta3_0.2mm_T240_B110_R0.85mm_RS50_EM0.9304_eSUN_Black_ABS+_Voron_v2_11h25m.arcw-400x300.png
[error] [2022-01-08T22:23:35.167Z] Error: Error: Request failed with status code 404
```

It should be:
```
http://127.0.0.1/server/files/gcodes/SUBFOLDERHERE/.thumbs/SB_CW2_beta3_0.2mm_T240_B110_R0.85mm_RS50_EM0.9304_eSUN_Black_ABS+_Voron_v2_11h25m.arcw-400x300.png
```

**Comment by eliteSchwein** [comment]
![image](https://user-images.githubusercontent.com/39838619/148731231-af318597-40ed-42cd-9857-272907bc85b0.png)
i tried to reproduce it, it worked for me just fine

**Comment by eliteSchwein** [comment]
fixed with febcff0f18b75d39c124cc4705fc8da7b95e646b
